# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5db3145a722e5ec4aa717b0ebc42253552510aa647116efc05419a0e8fcc0ac3fc7ee9795ccc72550c9d7f9b0d6e397fa29956062236dc3639ea732b852884c8

test:
  secret_key_base: 778365df8f4de0412f6fa3211900f3d7d0ca875047438970ceebb589a04575be14a226f89beb09a2950d7522ddb4acee6a7adc678c2e596cbb26522f6111b2ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
